package io.github.wesleyosantos91.api.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import io.github.wesleyosantos91.api.anotation.CustomGeneratedKey;
import io.github.wesleyosantos91.api.utils.converter.LocalDateConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "tb_person100")
public class Person implements Serializable {

    @DynamoDBHashKey
    @CustomGeneratedKey(prefix="PERSON#")
    private String id;

    @DynamoDBRangeKey
    private String cpf;

    @DynamoDBAttribute
    private String name;

    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @DynamoDBAttribute
    private LocalDate dateOfBirth;

    @DynamoDBAttribute
    private String email;
}
